### ISSUE TITLE
New library version

### ISSUE THREAD

**Issue by gidesa** [bitbank2/VL53L0X#4]
Hello,
I have done some modifications to the library.
Now it can be compiled as shared library (.so). 
More, I have added two functions: tofStartReadDist start a new reading and soon return to caller; tofReadDistanceAsync read the distance without any initial waiting cycle. That is, the reading is non blocking.
Using these functions a caller program can do other processing in the reading interval required by the device. The caller first call tofStartReadDist, then is responsible to call tofReadDistanceAsync after the minimum required interval to complete the reading operation, 200 ms or more.
Attached there is also a simple test program.
Hoping this will be useful

Giandomenico De Sanctis

[VL53L0X-nowait-sharedlib.zip](https://github.com/bitbank2/VL53L0X/files/6050407/VL53L0X-nowait-sharedlib.zip)

**Comment by bitbank2** [comment]
Thank you for creating this. I'm not currently working with this sensor on Linux, so I can't test what you've done. I would suggest you create a fork on your github account and host it there.
