### ISSUE TITLE
VL53L0X sensor With BeagleBone Black 

### ISSUE THREAD

**Issue by rajmehta28599** [bitbank2/VL53L0X#5]
**Aim:** C program to get VL53L0X sensor data using I2C communication in BeagleBone Black.

I am working with BeagleBone Black to get data from VL53L0X. I need help to the Made a header file and source file for that.

I think @bitbank2 your Contribution is near to my solution. So you help me with how I implement in BeagleBone Black.

**Issue:**
1) How to install the library.
2) which method to compile the c code.
3) how many changes I make in code. (like pin number, i2c bus.).

Thank you.

**Comment by bitbank2** [comment]
1. git clone
    make
2. gcc
3. None. The code is already written for Linux. You shouldn't need to change anything

**Comment by rajmehta28599** [comment]
_

```
_debian@beaglebone:~$ git clone https://github.com/bitbank2/VL53L0X.git
Cloning into 'VL53L0X'...
remote: Enumerating objects: 15, done.
remote: Total 15 (delta 0), reused 0 (delta 0), pack-reused 15
Unpacking objects: 100% (15/15), done.
debian@beaglebone:~$ cd VL53L0X/
debian@beaglebone:~/VL53L0X$ ls
LICENSE.txt  main.c  make_demo  Makefile  README.md  tof.c  tof.h
debian@beaglebone:~/VL53L0X$ make
cc -c -Wall -O2 tof.c
ar -rc libtof.a tof.o ;\
sudo cp libtof.a /usr/local/lib ;\
sudo cp tof.h /usr/local/include
debian@beaglebone:~/VL53L0X$ ls
libtof.a     main.c     Makefile   tof.c  tof.o
LICENSE.txt  make_demo  README.md  tof.h
debian@beaglebone:~/VL53L0X$ gcc main.c -o main.o
/usr/bin/ld: /tmp/ccKoXj4w.o: in function `main':
main.c:(.text+0x10): undefined reference to `tofInit'
/usr/bin/ld: main.c:(.text+0x38): undefined reference to `tofGetModel'
/usr/bin/ld: main.c:(.text+0x60): undefined reference to `tofReadDistance'
collect2: error: ld returned 1 exit status
debian@beaglebone:~/VL53L0X$_
```

_ 


unable to compile main.c.

Thank You.

**Comment by bitbank2** [comment]
The file "make_demo" is a makefile. To build it type: "make -f make_demo". It links main.c with the library you built.

**Comment by rajmehta28599** [comment]
```
_debian@beaglebone:~/VL53L0X$ ls
LICENSE.txt  main.c  main.o  make_demo  Makefile  README.md  tof.c  tofdemo  tof.h
debian@beaglebone:~/VL53L0X$ ./tofdemo
VL53L0X device successfully opened.
Model ID - 4851053
Revision ID - -1225052160
debian@beaglebone:~/VL53L0X$ ./tofdemo
VL53L0X device successfully opened.
Model ID - 4937069
Revision ID - -1224990720
debian@beaglebone:~/VL53L0X$ ./tofdemo
VL53L0X device successfully opened.
Model ID - 4461933
Revision ID - -1225355264_
```

How to get Sensor Range data ??

Thank you.

**Comment by rajmehta28599** [comment]
Thank you. Your Contribution is implemented in Beaglebone black Debian Os with C program.

Again thank you for your Contribution.

**Comment by rajmehta28599** [comment]
Hello @bitbank2 

Aim: Get Data from Multiple VL53L0X using I2C Communication.

your Code is for single VL53L0X data read. I am trying for multiple VL53L0X. but all VL53L0X have 0x29 I2C address. so to make a change in address so data can be differentiated. 

i try using: _`writeReg(0x8A,0x30);`_

I2C_SLAVE_DEVICE_ADDRESS = 0x8A
new device address = 0x30

Thank you.
