### ISSUE TITLE
How to change I2C Address in VL53L0X 

### ISSUE THREAD

**Issue by rajmehta28599** [bitbank2/VL53L0X#6]
AIM: Work with the 4-VL53L0X sensor using 1-I2C communication on BeagleBone Black.

I implement your contribution in BeagleBone Black for Single VL53L0X. 

But in My Application, I use 4 VL53L0X sensors.

And the issue is all VL53L0X have the same Slave Address 0x29. 

So, I think if I am able to change I2C Slave Address in VL53L0X then is Work.

Thank you.

**Comment by bitbank2** [comment]
I am no longer working with the VL53L0X. Please add the needed code and do a pull request if you would like to add the address change function to the library.
