### ISSUE TITLE
Hard to port to microcontrollers

### ISSUE THREAD

**Issue by FelipeSchneider** [bitbank2/VL53L0X#7]
Hi, this is not really a problem in the code if we only consider its original purpose, however, the use of the Linux _write()_ function, especially in the context of the function _writeRegList()_, makes it very hard to port to non-Linux microcontrollers.

The difficulty arises from the fact that whenever one is using I2C libraries such as the ones provided inside of ASF (Atmel/Microchip) it is not possible to start a transaction without sending first the address, or, it is not possible to avoid (or hold) the sending of a NACK.
Unfortunately, I only observed such incompatibility after a few days of work.

In any case, thank you for your time and desire to help others.

**Comment by bitbank2** [comment]
If you're not running the code on Linux, then I would go back to the original Polulu code that targets Arduino. It's probably an easier starting point.
